# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Build
# 
# Runs only on push events on branch 'master'
# 
on:
  push:
    branches:
      - master

# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
# 
# Workflow environment and steps
# 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Setup Java JDK
      # 
      - name: Setup JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: '11'
          distribution: 'zulu'
      # 
      # Run the build of project by ANT
      # 
      - name: Build
        run: ant buildAll
