# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Deploy
# 
# Runs only on new tag has been pushed
# and then publishes to gh-pages
# 
on:
  push:
    branches:
      - deploy
    tags:
      - '[0-9]+.[0-9]+'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 
# Workflow environment and steps
# 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 
      # Gets the tag to use as version
      # 
      - name: Get version
        id: version
        run: |
          echo "CHARBA_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Setup Java JDK
      # 
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      # 
      # Run the build of project by ANT
      # 
      - name: Build
        run: ant buildAll
      # 
      # Removes .gitignore
      # 
      - name: Remove .gitignore 
        run: rm -f ./war/.gitignore
      # 
      # Removes WEB-INF
      # 
      - name: Remove WEB-INF 
        run: rm -rf ./war/WEB-INF
      # 
      # Deploy showcase to GitHub Pages
      # 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./war
          enable_jekyll: false
          keep_files: false
          full_commit_message: Deploy ${{ steps.version.outputs.CHARBA_VERSION }} showcase to GitHub Pages