# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Deploy
# 
# Runs only on push events on branch 'deploy'
# and then publishes to gh-pages
# 
on:
   push:
      branches:
         - deploy
# 
# Workflow environment and steps
# 
jobs:
   deploy:
      runs-on: ubuntu-latest
      
      steps:
         # 
         # Checkout the repository content
         # 
         - name: Checkout
           uses: actions/checkout@v2
           with:
             # Disabling shallow clone 
             fetch-depth: 0
         # 
         # Setup Java JDK
         # 
         - name: Setup JDK
           uses: actions/setup-java@v2
           with:
             java-version: '11'
             distribution: 'adopt'
         # 
         # Run the build of project by ANT
         # 
         - name: Build
           run: ant buildAll
         # 
         # Removes .gitignore
         # 
         - name: Remove .gitignore 
           run: rm -f ./war/.gitignore
         # 
         # Removes WEB-INF
         # 
         - name: Remove WEB-INF 
           run: rm -rf ./war/WEB-INF
         # 
         # Deploy showcase to GitHub Pages
         # 
         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./war
             enable_jekyll: false
             keep_files: false
             full_commit_message: Deploy 4.0 showcase to GitHub Pages